UNITTESTPATH 	:= UnitTest
OBJ				:= ./obj
UNITTESTSRC		:= $(UNITTESTPATH)/src

UNITTESTSOURCE 	+= 
UNITTESTSOURCE  += $(UNITTESTPATH)/src/TestSuite1.c
UNITTESTSOURCE  += $(UNITTESTPATH)/src/TestSuite2.c
UNITTESTSOURCE  += $(UNITTESTPATH)/src/TestSuite3.c
UNITTESTSOURCE  += $(UNITTESTPATH)/src/TestSuites.c

UNITESTINCLUDE 	= $(UNITTESTPATH)/include

UNITTESTOBJS 	= $(patsubst $(UNITTESTPATH)/src/%.c,$(OBJ)/%.o,$(UNITTESTSOURCE))
