UNITTESTRUNNERPATH 		:= UnitTestRunner
OBJ						:= ./obj
UNITTESTRUNNERSRC		:= $(UNITTESTRUNNERPATH)/src

UNITTESTRUNNERSOURCE 	= $(wildcard $(UNITTESTRUNNERSRC)/*.c)

UNITESTRUNNERINCLUDE 	= $(UNITTESTRUNNERPATH)/include

UNITTESTRUNNEROBJS 		= $(patsubst $(UNITTESTRUNNERPATH)/src/%.c,$(OBJ)/%.o,$(UNITTESTRUNNERSOURCE))
