UNITTESTRUNNERPATH 		:= UnitTestRunner
OBJ						:= ./obj
UNITTESTRUNNERSRC		:= $(UNITTESTRUNNERPATH)/src

UNITTESTRUNNERSOURCE 	+= 
UNITTESTRUNNERSOURCE 	+= $(UNITTESTRUNNERPATH)/src/main.c
UNITTESTRUNNERSOURCE 	+= $(UNITTESTRUNNERPATH)/src/UnitTestFramework.c

UNITESTRUNNERINCLUDE 	= $(UNITTESTRUNNERPATH)/include

UNITTESTRUNNEROBJS 		= $(patsubst $(UNITTESTRUNNERPATH)/src/%.c,$(OBJ)/%.o,$(UNITTESTRUNNERSOURCE))
